version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'dashboard-company-db'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db  

  api:
    container_name: dashboard-company-api
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db    
    volumes:
      - "./api/src:/home/node/api/src"
      - "./api/public:/home/node/api/public"

volumes:
  pg-data:
  